### ISSUE TITLE
[Bug] Fallback to Home Assistant Local login appears to fail

### ISSUE THREAD

**Issue by KairuByte** [BeryJu/hass-auth-header#105]
During setup of SSO I ran into #104, which meant that I was unable to properly auth through SSO.

After getting things into a near workable state in the hopes that the feature can be added at some point, I moved on to ensuring things would work if left in the current state where two logins  (SSO and Home Assistant Local) are required.

However, it seems that no matter how I access the login page, it is impossible to authenticate through Home Assistant Local. Removing Header Auth seems to correct this problem.

**Comment by patrik996** [comment]
I'm having the same issue. Behind Swag/Authelia.
