### ISSUE TITLE
Login Flow creates new Tokens every time

### ISSUE THREAD

**Issue by jhbruhn** [BeryJu/hass-auth-header#151]
I have successfully configured this plugin using traefik and authelia and it is working nicely.

Unfortunately, it seems that the integration creates a new login token every time I visit my HA instance via the browser, or at least every time a new authelia session is started (although I am using "Remember me" login).

Is this intended? Would it be possible to change the behaviour of the integration so it only generates a new token once, or at least deletes the old token from HA when it is generating a new one?

**Comment by jhbruhn** [comment]
It seems that the token is not stored on client side, at least on the web fronted (the android app successfully stores the token). I do not understand HAs architecture well enough, but it seems this parameter is somehow missing? https://github.com/home-assistant/frontend/blob/5160a1f55cda94008ca15380b6307b63ca09274b/src/auth/ha-auth-flow.ts#L305

**Comment by BeryJu** [comment]
Probably, I haven't really looked into the HASS auth code that this is based on in a while

**Comment by jhbruhn** [comment]
I "fixed" this by adding a custom lovelace JavaScript-resource which contains the code snippet mentioned above.

**Comment by fOmey** [comment]
> I "fixed" this by adding a custom lovelace JavaScript-resource which contains the code snippet mentioned above.

Could you share and go in a little more detail on how to do this please?
