### ISSUE TITLE
Matching user by standard credential username instead of displayname?

### ISSUE THREAD

**Issue by tgolsson** [BeryJu/hass-auth-header#23]
Hello, thanks for the great integration! I'm a bit curious if you've considered using the default credentials name (username) of Home Assistant for authentication instead of the "display name". While of course one can configure any mapping on either end and any header, I'd expect it to match on the name I use to login by default.

**Comment by BeryJu** [comment]
Hi,

I'm not quite sure I understand your question, do you mean [this](https://github.com/BeryJu/hass-auth-header/blob/master/custom_components/auth_header/headers.py#L91) part?

Most of that file I've copied from the TrustedNetworksAuthProvider and adjusted to taking the username value from the header.

**Comment by tgolsson** [comment]
Sorry, I mean this part: 

https://github.com/BeryJu/hass-auth-header/blob/65ace8caebcb4408175f35f71e02eb7dc10fd738/custom_components/auth_header/headers.py#L148-L150

This means that if I fill in this screen:

![image](https://user-images.githubusercontent.com/8234817/107151833-0c113600-6965-11eb-8498-ceb3692fb39f.png)


```
Name: Tom Solberg
Username: me@some-address.foo
Password: abc123
```

The observed behaviour tries to match the authentication value with `Tom Solberg` and not `me@some-address.foo` which makes more sense to me.

**Comment by BeryJu** [comment]
Right, good question, I think I had a reason for this when I originally wrote the code. I'll do some debugging to check what the reasoning was.

**Comment by BeryJu** [comment]
After some quick debugging I remembered why,

https://github.com/BeryJu/hass-auth-header/blob/65ace8caebcb4408175f35f71e02eb7dc10fd738/custom_components/auth_header/headers.py#L61

`async_get_users` returns a list of User objects which only have an ID and the full name but not the username.

They do however have `.credentials` which is a list of Credential objects, which can hold a username.

**Comment by BeryJu** [comment]
@tgolsson I've added this in https://github.com/BeryJu/hass-auth-header/releases/tag/v1.3, thanks for the issue.
