### ISSUE TITLE
Integration error: auth_header - Integration 'auth_header' not found.

### ISSUE THREAD

**Issue by nicedevil007** [BeryJu/hass-auth-header#232]
Hi, I added the repo `https://github.com/BeryJu/hass-auth-header` to HACS and then restarted HASS.
Afterwards I added this to my HASS configuration.yaml

```
auth_header:
  username_header: X-authentik-username
```

This ends with a not restartable HASS with the error message in the title. I also tried to find an integration after adding the repo with "hass-auth-header" but nothing can be found.

**Comment by BeryJu** [comment]
Search for "Header Authentication" in HACS

**Comment by nicedevil007** [comment]
> Search for "Header Authentication" in HACS

Found it now, removed the repo and installed it again then I was able to find your addon! Thank you :)
