### ISSUE TITLE
Can't login with authentik setup

### ISSUE THREAD

**Issue by nicedevil007** [BeryJu/hass-auth-header#236]
I created the configuration from authentik as it is described in the documentation now but I still can't login:

In this example I use this environment:
10.0.4.248 => nginx proxy manager
10.0.4.238 => authentik

The message in the browser looks like this:
![image](https://user-images.githubusercontent.com/17103076/221230079-9ecde8ed-7c05-47d1-afac-370a670f1c8f.png)

the log shows this:
`2023-02-24 17:07:58.083 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.0.4.248 (10.0.4.248). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50)`

and this is my entry in configuration.yaml
```python
logger:
  default: info
  logs:
    custom_components.auth_header: debug

http:
  server_port: 8123
  cors_allowed_origins:
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.4.248/32
    - 10.0.4.238/32
  ip_ban_enabled: true
  login_attempts_threshold: 5

auth_header:
  username_header: X-Authentik-Username
  debug: true
```

Yes the username is 100% identical in homeassistant and authentik

**Comment by guilfoos** [comment]
I'm seeing the exact same problem. I know my Authentik installation is working (for OAuth logins), but I'm seeing this exact same behavior for Home Assistant's proxy login via Authentik. The only diferences in my config from the one posted here is that I've commented out the IP ban directives, and I don't have cors_allowed_origins. Unfortunately, I cannot make sense of the log issues.

I understand this doesn't work well on the Android app anyway, so I might abandon it and go back to app auth, but federated logins and MFA are very attractive. I'd like to figure this out.

**Comment by guilfoos** [comment]
Digging further, it appears that the first time it tries to load Home Assistant after Authentik it gets a 400 error (bad request) for the websocket.

 DEBUG (MainThread) [custom_components.auth_header] <CIMultiDictProxy('X-authentik-username': '*****', 'X-authentik-email': '*****@gmail.com', 'X-authentik-name': '*****', 'X-authentik-uid': '349ca*****', 'X-Forwarded-For': '10.76.30.136', 'Host': 'homeassistant.local:8123', 'Connection': 'close', 'Content-Length': '151', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0', 'Accept': '*/*', 'Accept-Language': 'en-GB,en;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://homeassistant.domain.tld/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fhomeassistant.domain.tld%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fhomeassistant.domain.tld%2F&state=eyJoYX*****', 'Content-Type': 'text/plain;charset=UTF-8', 'Origin': 'https://homeassistant.domain.tld', 'dnt': '1', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'Cookie': 'authentik_proxy_Nyoju6*****')>
2023-03-08 10:26:46.811 DEBUG (MainThread) [custom_components.auth_header] Got actual IP 10.76.0.12

The "Actual IP" is my Nginx Proxy Manager. NOT the end client. The X-Forwarded-For reported by auth_header is my client IP.

After that first attempt, when Home Assistant tries to connect again 60 seconds later (and every time after that) I get a 400 bad request error on homeassistant.domain.tld/auth/token.

I don't seem to see an "X-Forwarded-For" header in the request headers for the websocket call when I inspect my browser. What's curious about this is that if I remove Authentik from the flow, things work. In Authentik, I'm doing a forward auth proxy provider with implicit consent flow. I'm a pretty clever person, but this is getting into the guts of stuff I just don't know a lot about.

**Comment by guilfoos** [comment]
Yep, that was the fix. I added these lines to the main location / {} block in NPM:

    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

**Comment by nicedevil007** [comment]
> Yep, that was the fix. I added these lines to the main location / {} block in NPM:
> 
> ```
> proxy_set_header Host $host;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```

mhhh thank you first but maybe I still can't get the point. I opened the WebUI of NginxProxyManager now and created a new Custom Location for my HomeAssistant like this:

![image](https://user-images.githubusercontent.com/17103076/225421935-5d1203b5-babb-4243-aefe-af053b79dc7c.png)

But it is still the same for me :/

**Comment by guilfoos** [comment]
If you hover over the red dot it should pop up the error. Did you delete the location you added to the "location" tab? If not, you've got multiple "location /" blocks (the error will be "duplication location"). Delete that location, and leave the stuff in the Advanced tab.

**Comment by nicedevil007** [comment]
> proxy_set_header Host $host;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";

yeah I only got the one on advanced now

didn't know that feature with hovering over "offline" :D thank you! 
![image](https://user-images.githubusercontent.com/17103076/225427545-e659fd8c-59d0-4fd0-9af1-37a17097ccae.png)

**Comment by nicedevil007** [comment]
lol ok.... found the issue... god damn.... 

I copied this line of code as well :/

![Uploading image.png…]()

**Comment by nicedevil007** [comment]
> I am having the same problem. Can you post your full config that ended up working for you in npm?

I guess you haven't changed the authentik dns in the `location /outpost.goauthentik.io`

we assume you have the following DNS for your authentik instance: authentik.mydomain.com and the internal IP adress 10.0.0.5 with the listening port 9443 then you have to change this line:

```python
location /outpost.goauthentik.io {
    proxy_pass              https://authentik.mydomain.com/outpost.goauthentik.io;
```

to this:

```python
location /outpost.goauthentik.io {
    proxy_pass              https://10.0.0.5:9443/outpost.goauthentik.io;
```

**Comment by ModeratePrawn** [comment]
That did it! Thank you so much! This was my answer after two days of trying.
