### ISSUE TITLE
ERROR adding to repository to HACS

### ISSUE THREAD

**Issue by Mrs-Feathers** [BeryJu/hass-auth-header#286]
Error: https://github.com/BeryJu/hass-auth-header is not a valid add-on repository

**Comment by Mrs-Feathers** [comment]
requires a "repository.yaml" to be added to the repo now.

example file:

name: pschmitt's addon repository
url: https://github.com/pschmitt/home-assistant-addons
maintainer: Philipp Schmitt <philipp@schmitt.co>

**Comment by BeryJu** [comment]
repository.yaml is required for add-on repositories (https://developers.home-assistant.io/docs/add-ons/repository/) which is not what this repository is. Add the repo in HACS under Integrations -> 3-dot menu -> Custom repositories
