### ISSUE TITLE
Help with Cloudflare tunnel -> authentik -> HASS

### ISSUE THREAD

**Issue by panteLx** [BeryJu/hass-auth-header#297]
Hey, 

I need some help with configuring the following setup:

I use cloudflare tunnel as my reverse proxy. It's setup to login (via cloudflare access) via authentik (on websites that don't support oAuth). 
I want to set the cloudflare output as my header credentials for home assistant but it won't work. I don't know if this is in issue related to cloudflare tunnel (do they even support header auth?). 

Is there a way to do that ? :D I need cloudflare as my reverse proxy. Anything else is not required for a working setup. 

Or is it even possible to "deactivate" home assistant auth and use the cloudflare access auth instead?

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I have the same setup and the same problem.

**Comment by panteLx** [comment]
I switched to the LDAP auth provider. Check out my repo to get more infos. It's easier and the app works.
