### ISSUE TITLE
Version key in manifest

### ISSUE THREAD

**Issue by yeyeoke** [BeryJu/hass-auth-header#32]
Hi! Since I've updated to the latest version of homeassistant I noticed this error in the logs: 

ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'auth_header'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'auth_header'
It seems to be related to this so I thought I'd just give you a heads up so nothing breaks when 2021.6 is released. 

https://github.com/home-assistant/core/pull/49726

Thank you so much for this integration, finally got SSO working for my family thanks to this.

**Comment by BeryJu** [comment]
Cheers, added the version manifest and pushed v1.4
