### ISSUE TITLE
HTTP Status Codes moved in HA Core

### ISSUE THREAD

**Issue by PotentialIngenuity** [BeryJu/hass-auth-header#94]
https://github.com/home-assistant/core/pull/58380

This is causing HA to throw the following error
`ERROR (MainThread) [homeassistant.setup] Setup failed for auth_header: Unable to import component: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by BeryJu** [comment]
Should be fixed in the latest tagged version

**Comment by PotentialIngenuity** [comment]
That was the fix
